spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:/scripts/schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

    show-sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
